### PR TITLE
Fix sqrt(negative value) by adding q_0 variable within Plant

### PR DESCRIPTION
**Pull request by quackduck**
Added a q_0 variable within the Plant (making the state 13 values long) so we're never taking the square root of a negative number (which was happening because we were generating q_0 on the go and errors were accumulating) and made sure the magnitude of the quaternion stays 1.

### CODE REVIEW

**Comment by quackduck** [comment]
Wait why did this get closed

**Comment by QuackingBob** [comment]
Sorry about that, my username is quacking bob (similar to yours which is quack duck) and I had published a branch yesterday so when I saw the github pull request, I got confused and thought that I accidentally made a pull request (the messages for the pull request and the new branch overlapped on github and it was asking if I wanted to make a pull request) so I closed it by accident.

**Comment by quackduck** [comment]
lol no worries

**Review by anigokhale — APPROVED** [review]
Looks good

**Comment by quackduck** [comment]
Wait did this get merged or closed

**Pull request merged**
